services:
  db:
    image: postgres:15-alpine
    container_name: whatsappcrm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - TZ=Africa/Harare # <-- Added timezone
      - POSTGRES_DB=${DB_NAME:-whatsapp_crm_dev}
      - POSTGRES_USER=${DB_USER:-crm_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?Please set DB_PASSWORD in .env file}
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgbouncer:
    image: pgbouncer/pgbouncer:latest
    container_name: whatsappcrm_pgbouncer
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    ports:
      - "6432:6432" # Expose PgBouncer on a different port
    depends_on:
      - db
    environment:
      - TZ=Africa/Harare
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: whatsappcrm_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: ./whatsappcrm_backend
    container_name: whatsappcrm_backend_app
    volumes:
      - ./whatsappcrm_backend:/app
      - staticfiles_volume:/app/staticfiles
    environment: # <-- Added environment section
      - DB_HOST=pgbouncer # <-- Point to PgBouncer
      - TZ=Africa/Harare
    env_file:
      - ./whatsappcrm_backend/.env
    depends_on:
      - db
      - pgbouncer
      - redis
    restart: unless-stopped

  frontend:
    build: ./whatsapp-crm-frontend
    container_name: whatsappcrm_frontend_app
    environment:
      - DB_HOST=pgbouncer
      - TZ=Africa/Harare
    depends_on:
      - backend
    restart: unless-stopped

  celery_worker:
    build: ./whatsappcrm_backend
    container_name: whatsappcrm_celery_worker_io
    command: celery -A whatsappcrm_backend worker -l INFO -P eventlet -c 1000 -Q celery
    volumes:
      - ./whatsappcrm_backend:/app
    environment: # <-- Added environment section
      - DB_HOST=pgbouncer # <-- Point to PgBouncer
      - TZ=Africa/Harare
    env_file:
      - ./whatsappcrm_backend/.env
    depends_on:
      - redis
      - pgbouncer
      - db
    restart: unless-stopped

  celery_worker_cpu:
    build: ./whatsappcrm_backend
    container_name: whatsappcrm_celery_worker_cpu
    command: celery -A whatsappcrm_backend worker -l INFO -P prefork -c 2 -Q cpu_intensive
    volumes:
      - ./whatsappcrm_backend:/app
    environment: # <-- Added environment section
      - DB_HOST=pgbouncer # <-- Point to PgBouncer
      - TZ=Africa/Harare
    env_file:
      - ./whatsappcrm_backend/.env
    depends_on:
      - redis
      - pgbouncer
      - db
    restart: unless-stopped

  celery_beat:
    build: ./whatsappcrm_backend
    container_name: whatsappcrm_celery_beat
    command: celery -A whatsappcrm_backend beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./whatsappcrm_backend:/app
    environment: # <-- Added environment section
      - DB_HOST=pgbouncer # <-- Point to PgBouncer
      - TZ=Africa/Harare
    env_file:
      - ./whatsappcrm_backend/.env
    depends_on:
      - redis
      - pgbouncer
      - db
    restart: unless-stopped

  nginx_proxy:
    image: nginx:1.25-alpine
    container_name: whatsappcrm_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles_volume:/srv/www/static/:ro
      - ./whatsappcrm_backend/mediafiles:/srv/www/media/:ro
      - /var/www/letsencrypt:/var/www/letsencrypt:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    environment:
      - DB_HOST=pgbouncer
      - TZ=Africa/Harare
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  staticfiles_volume:
